version: '3.8'


services:
  bot:
    container_name: bot
    build:
      context: .
    #image: anton60874022/bot:latest
    command: bash -c "python nko_bot.py"
    restart: always
    depends_on:
      - mongodb
    networks:
      - db_network
    env_file:
      - .env
    volumes:
      - log_dir:/app/log_dir


  admin:
    container_name: admin
    build:
      context: .
    #image: anton60874022/admin:latest
    command: bash -c "uvicorn admin.main:app"
    restart: always
    depends_on:
        - mongodb
    networks:
        - db_network
    env_file:
        - .env



  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - db_network
    command: [--auth]
    env_file:
      - .env
    volumes:
      - log_dir:/app/log_dir
      - mongo_config:/etc/


  nginx:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - admin
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - ./conf.d:/etc/nginx/conf.d


    networks:
      - db_network

volumes:
  log_dir:
  static_value:
  mongo_config:


networks:
  db_network:
